### ISSUE TITLE
[Bug] Unused variables in Header.astro

### ISSUE THREAD

**Issue by lguima** [lancerossdev/nofuss#3]
Should we replace them in the nav iteraction? Or can we removed them?

```
const desktopIcons = "dark:text-zinc-300 text-black hover:text-zinc-500 dark:hover:text-zinc-400 hidden sm:block";
const mobileIcons = "dark:text-zinc-300 text-black hover:text-zinc-500 dark:hover:text-zinc-400 sm:hidden";
```
> https://github.com/lancerossdev/nofuss/blob/main/src/components/Header.astro#L23

```
<a href={navbar.href} class="dark:text-zinc-300 text-black hover:text-zinc-500 dark:hover:text-zinc-400 hidden sm:block">
```
> https://github.com/lancerossdev/nofuss/blob/main/src/components/Header.astro#L36

```
<a href={navbar.href} class="dark:text-zinc-300 text-black hover:text-zinc-500 dark:hover:text-zinc-400 sm:hidden">
```
> https://github.com/lancerossdev/nofuss/blob/main/src/components/Header.astro#L52

**Comment by lancerossdev** [comment]
Hello there,

Hmm I see. I will try to update it once I got time maintaining this project again (I don't know when though, I'm always busy with other things eh). Thanks for raising an issue about this, I will keep track of it.

**Comment by lguima** [comment]
Sure, if you could leave any directions on how you recommend fixing it (removing or using it indeed), I could do that.

**Comment by lancerossdev** [comment]
Hey again, you can create a pull request for this. It's just a simple unused variables but still, it helps a lot!

You can remove the current class from the `<a>` tags and replace it with `class={variablename}`. Here's an example.

```astro
<a href={navbar.href} class={desktopIcons}> 
   {navbar.name}
</a>
```

I will try to maintain this project again maybe in saturday when I got time 😄!
