### ISSUE TITLE
Demo link is broken

### ISSUE THREAD

**Issue by lguima** [lancerossdev/nofuss#4]
[nofuss.vercel.app](https://nofuss.vercel.app)

```
404: NOT_FOUND
Code: DEPLOYMENT_NOT_FOUND
ID: gru1::...

nofuss.vercel.app might be available. Click here to learn how to assign it to a project.
```

**Comment by lancerossdev** [comment]
Hello there!

I just deleted the demo link because I don't know if I should still maintain this project or abandoned it. I will try to update and create a new demo link once I got time! Sorry for the inconvenience.

Regards,
Lance

**Comment by lguima** [comment]
Got it, no worries! Maybe using the [GitHub pages](https://pages.github.com/) can be an alternative.

**Comment by lancerossdev** [comment]
Hey @lguima, I just deployed the template on [nofuss.pages.dev](https://nofuss.pages.dev). Wait for a few minutes, I'm having errors on build 😅

**Comment by c3z** [comment]
@lancerossdev plese check here: https://github.com/natemoo-re/astro-icon/issues/65#issuecomment-1309552916

**Comment by lancerossdev** [comment]
> @lancerossdev plese check here: https://github.com/natemoo-re/astro-icon/issues/65#issuecomment-1309552916

Thanks for mentioning it! I'll try to work with it later.

**Comment by lancerossdev** [comment]
Alright, the site is now deployed at https://nofuss.pages.dev/
